### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by DaveBlooman** [apcera/termtables#26]
I have used termtables in my app, when I try to compile for Linux, I get the error no buildable Go source files in /path/to/go/src/github.com/apcera/termtables/locale

Im using Gox to compile

**Comment by krobertson** [comment]
I'd recommend just using `go build` on the target platform. From our experience, cross compiling in Go is problematic anytime cgo starts to be involved. It can work well when compiling a 32bit linux binary on a 64bit system, but we found too many issues with cross platform.

**Comment by krobertson** [comment]
@DaveBlooman FYI, I think was actually fixed in #27. I thought we were building against this on Windows natively, but I was wrong and we were also cross compiling. So guess we were victims as well.

We were cross compiling on Linux to get a Windows binary, which it sounds like you were as well. Perhaps try with the latest code, or can look a bit further.

**Comment by akaroot** [comment]
I have the same issue when trying to build for amd64 on 32 bit linux.

`table.go:8:2: no buildable Go source files in .../github.com/apcera/termtables/locale`

**Comment by johnSchnake** [comment]
cgo in the `locale` package was removed in #37 .

Also, just FYI cgo is also being removed from the rest of the packages too in #42 .
