### ISSUE TITLE
Have issues with Chinese and Japanese characters.

### ISSUE THREAD

**Issue by kurtzhong** [apcera/termtables#33]
Generally this package does its job very well, just a little issue with CJK characters, is it because the package can't calculate the length of CJK strings properly?

Example output 1:

```
 +-------+---------+---------+---------+
| KeyID | ValueID | ValueCN | ValueJP |
+-------+---------+---------+---------+
| 8     | 41      | 蜥蜴皮     |         |
| 8     | 42      | 硅胶      |         |
| 8     | 43      | 橡胶      |         |
| 8     | 44      | 陶瓷      |         |
| 8     | 45      | 钛合金     |         |
| 8     | 46      | 钯金      |         |
| 8     | 47      | 玫瑰金     |         |
| 8     | 48      | 白金      |         |
| 8     | 49      | 黄金      |         |
| 8     | 50      | 镀金      |         |
| 8     | 51      | 精钢      |         |
| 8     | 52      | 鳄鱼皮     |         |
| 8     | 53      | 镀金皮带    |         |
| 8     | 54      | 精钢      |         |
| 8     | 68      | 牛皮      |         |
| 8     | 69      | 鳄鱼皮     |         |
+-------+---------+---------+---------+

```

Example output 2:

```
+--------------------+------------+
| field              | value      |
+--------------------+------------+
| GoodsPropertyKeyID | 9          |
| MerchantAccountID  | 0          |
| GoodsCategoryCode  | 100001     |
| NameCN             | 机芯类型       |
| NameJP             | ムーブメントのタイプ |
| IsMultiple         | false      |
| IsPrimary          | false      |
+--------------------+------------+

```

**Comment by krobertson** [comment]
I'll take a look. It may be that counting the UTF-8 runes isn't handling double width characters or something.

**Comment by philpennock** [comment]
This is a known issue, known at the time that the current width calculation code was written:

https://github.com/apcera/termtables/blob/master/cell.go#L60-L69

None of the people who were around in Apcera at the time were familiar with CJK and rather than pick a poor technology through ignorance, we left it as a future enhancement.

Does anyone have suggestions of an appropriate library/approach to use in Golang for text-handling and calculating "width" of text, assuming monospace fonts and no glyph rendering control?

**Comment by philpennock** [comment]
Vim handles this for the `strwidth` vimscript function by using custom string-length measuring, which goes through each Unicode character in turn, adding the "cell width" of each character.  It does this using hard-coded tables of Unicode codepoint ranges which are "not 1".

See `utf_char2cells` in vim's `src/mbyte.c` file; at current time, this is:
https://github.com/vim/vim/blob/44d571868f4fcf000e8b03ee0a350f1f8131c9ca/src/mbyte.c#L1218-L1469

As noted therein, `runtime/tools/unicode.vim` is used to generate these; it parses the Unicode release files.  This could be used for a `go generate` approach.

Should look to see if there already exists a decent Unicode library of extended properties for Golang, beyond what's in the standard library, to support this.  If not, then this logic belongs in a new package upon which `termtables` can depend, instead of being embedded in this package.

https://godoc.org/golang.org/x/text/width comes close, but doesn't look like it's right, unless we iter over the `Kind` and dispatch to increment by 2 sometimes.
